# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MainScreen(object):
    def setupUi(self, MainScreen):
        MainScreen.setObjectName("MainScreen")
        MainScreen.resize(900, 500)
        MainScreen.setMinimumSize(QtCore.QSize(900, 500))
        MainScreen.setMaximumSize(QtCore.QSize(900, 500))
        MainScreen.setAutoFillBackground(False)
        self.tabla_imagenes = QtWidgets.QTabWidget(MainScreen)
        self.tabla_imagenes.setGeometry(QtCore.QRect(0, 0, 901, 501))
        self.tabla_imagenes.setStyleSheet("")
        self.tabla_imagenes.setObjectName("tabla_imagenes")
        self.carga_imagenes = QtWidgets.QWidget()
        self.carga_imagenes.setObjectName("carga_imagenes")
        self.btn_carga = QtWidgets.QPushButton(self.carga_imagenes)
        self.btn_carga.setGeometry(QtCore.QRect(10, 410, 141, 41))
        self.btn_carga.setObjectName("btn_carga")
        self.tableWidget = QtWidgets.QTableWidget(self.carga_imagenes)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 881, 391))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tabla_imagenes.addTab(self.carga_imagenes, "")
        self.procesasdo_imagenes = QtWidgets.QWidget()
        self.procesasdo_imagenes.setObjectName("procesasdo_imagenes")
        self.btn_destino = QtWidgets.QPushButton(self.procesasdo_imagenes)
        self.btn_destino.setGeometry(QtCore.QRect(10, 410, 141, 41))
        self.btn_destino.setObjectName("btn_destino")
        self.btn_procesar = QtWidgets.QPushButton(self.procesasdo_imagenes)
        self.btn_procesar.setGeometry(QtCore.QRect(740, 410, 141, 41))
        self.btn_procesar.setCheckable(False)
        self.btn_procesar.setObjectName("btn_procesar")
        self.label_destino = QtWidgets.QLabel(self.procesasdo_imagenes)
        self.label_destino.setGeometry(QtCore.QRect(160, 410, 521, 41))
        self.label_destino.setObjectName("label_destino")
        self.progress_bar_tratamiento = QtWidgets.QProgressBar(self.procesasdo_imagenes)
        self.progress_bar_tratamiento.setGeometry(QtCore.QRect(10, 370, 871, 23))
        self.progress_bar_tratamiento.setProperty("value", 0)
        self.progress_bar_tratamiento.setObjectName("progress_bar_tratamiento")
        self.tabla_procesado = QtWidgets.QTableWidget(self.procesasdo_imagenes)
        self.tabla_procesado.setGeometry(QtCore.QRect(10, 10, 881, 351))
        self.tabla_procesado.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabla_procesado.setAutoFillBackground(False)
        self.tabla_procesado.setObjectName("tabla_procesado")
        self.tabla_procesado.setColumnCount(2)
        self.tabla_procesado.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_procesado.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_procesado.setHorizontalHeaderItem(1, item)
        self.tabla_procesado.horizontalHeader().setStretchLastSection(True)
        self.tabla_imagenes.addTab(self.procesasdo_imagenes, "")

        self.retranslateUi(MainScreen)
        QtCore.QMetaObject.connectSlotsByName(MainScreen)

    def retranslateUi(self, MainScreen):
        _translate = QtCore.QCoreApplication.translate
        MainScreen.setWindowTitle(_translate("MainScreen", "Coloreado de imágenes"))
        self.btn_carga.setText(_translate("MainScreen", "Cargar imagenes"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainScreen", "Imagen"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainScreen", "Path"))
        self.tabla_imagenes.setTabText(self.tabla_imagenes.indexOf(self.carga_imagenes), _translate("MainScreen", "Carga de imagenes"))
        self.btn_destino.setText(_translate("MainScreen", "Seleccionar destino"))
        self.btn_procesar.setText(_translate("MainScreen", "Procesar imagenes"))
        self.label_destino.setText(_translate("MainScreen", "Destino: "))
        item = self.tabla_procesado.horizontalHeaderItem(0)
        item.setText(_translate("MainScreen", "Imagen"))
        item = self.tabla_procesado.horizontalHeaderItem(1)
        item.setText(_translate("MainScreen", "Path"))
        self.tabla_imagenes.setTabText(self.tabla_imagenes.indexOf(self.procesasdo_imagenes), _translate("MainScreen", "Procesado de imagenes"))
